sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t saimirgasa/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true saimirgasa/react-test npm test

after_success:
  - docker build -t saimirgasa/multi-client ./client
  - docker build -t saimirgasa/multi-nginx ./nginx
  - docker build -t saimirgasa/multi-server ./server
  - docker build -t saimirgasa/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push saimirgasa/multi-client
  - docker push saimirgasa/multi-nginx
  - docker push saimirgasa/multi-server
  - docker push saimirgasa/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-792027914920
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  